DROP TABLE IF EXISTS client CASCADE;

DROP SEQUENCE IF EXISTS client_seq;

CREATE SEQUENCE public.client_seq start 1;

CREATE TABLE worker(
   ID INTEGER PRIMARY KEY,
   NAME VARCHAR(1000) CHECK(CHAR_LENGTH(NAME)>2) NOT NULL,
   BIRTHDAY DATE CHECK (1900 < extract(year from BIRTHDAY)),
   LEVEL VARCHAR CHECK(LEVEL IN ('Trainee', 'Junior', 'Middle', 'Senior')) NOT NULL,
   SALARY INTEGER CHECK(SALARY>100 AND SALARY<100000)
);

CREATE TABLE client(
   ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('client_seq'),
   NAME VARCHAR(1000) CHECK(CHAR_LENGTH(NAME)>2) NOT NULL
);

CREATE TABLE project(
   ID INTEGER PRIMARY KEY,
   CLIENT_ID INTEGER,
   START_DATE DATE,
   FINISH_DATE DATE
);

CREATE TABLE project_worker(
  PROJECT_ID INTEGER,
  WORKER_ID INTEGER,
  PRIMARY KEY (PROJECT_ID, WORKER_ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES project(id),
  FOREIGN KEY (WORKER_ID) REFERENCES worker(id)
);
